#pragma config(Sensor, S1,     HTSPB,                sensorI2CCustom9V)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "HTSPB-driver.h"

task main()
{
float inputData;
float min = 360;
float max = -360;

  while(true) {

  	// Read a 10 bit wide analogue value from A0
    inputData = HTSPBreadADC(HTSPB, 0, 10);
    // convert to original
		inputData = (inputData*0.703125)-360;

    displayTextLine(1, "A0: %f", inputData);
    if (inputData< min){
    	min = inputData;
    }
    if (inputData > max){
    	max = inputData;
    }
    wait1Msec(250);
    displayTextLine(2, "Min: %f", min);
    displayTextLine(3, "Max: %f", max);
	}
}
