#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S2,     HTSPB,          sensorI2CCustom9V)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//uncomment and set values for Ki and Kd to make the program full PID (not recommended for turning)
#include "HTSPB-driver.h"
void gyroTurn (int GOAL)
{

int Kp = 0.75;

//int Ki = ;
//int integral = 0;

//int Kd = ;
//int lastError = 0;
//int derivative = 0;

int Turn = 0;
int gyroVal = HTSPBreadADC(HTSPB, 0, 10);
gyroVal = (gyroVal*0.703125)-360;
int error = GOAL + gyroVal;
int rError = error;
	while(abs(error) > 1){
	gyroVal = HTSPBreadADC(HTSPB, 0, 10);
	gyroVal = (gyroVal*0.703125)-360;
	error = rError - gyroVal;
	//integral = ((2/3)*integral) + error;
	//derivative = error - lastError;

	//Turn = (Kp*error) + (Ki*integral) + (Kd*derivative);
	Turn = (Kp*error);
	motor[motorD] = (Turn);
	motor[motorE] = (Turn);
	motor[motorF] = (-Turn);
	motor[motorG] = (-Turn);
	//lastError = error;
	}
}

task main()
{
	gyroTurn(90);
}
